version: '3'
    services:
      web:
        image: nginx:1.15.6
        ports:
          - "8000:80"
        depends_on:
          - app
        volumes:
          - ./web/default.conf:/etc/nginx/conf.d/default.conf
          - ./src:/var/www/
      app:
        build: ./php
        depends_on:
          - mysql
        volumes:
          - ./src:/var/www/
      mysql:
        image: mysql:5.7
        environment:
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - "3306:3306"
        volumes:
          - ./mysql/mysql-data:/var/lib/mysql
      workspace:
        build: ./workspace
        volumes:
         - ${APP_CODE_PATH_HOST}:/var/www/
        ports:
         - "22:22"
